version: '2.1'
volumes:
  user_uploads:
  wooey_db:

services:
  wooey:
    extends:
      file: docker-compose.common.yml
      service: common
    ports:
      - 8081:8080
    depends_on:
      - rabbit
      - db
    command: ./run-server

  celery:
    extends:
      file: docker-compose.common.yml
      service: common
    command: celery worker -A docker_wooey -c 4 -B -l debug -s schedule

  rabbit:
    image: rabbitmq:3.7.15

  db:
    image: postgres:11.3
    volumes:
      - wooey_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wooey
      POSTGRES_PASSWORD: wooey
      POSTGRES_DB: wooey
